version: '3.8'

services:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - kafka-data:/bitnami/kafka

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  gateway:
    image: sshewalkar4094/telemetry-ingestor:latest
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - redis
    environment:
      - KAFKA_BROKERS=kafka:9092
      - REDIS_ADDR=redis:6379
      - KAFKA_TOPIC=telemetry
      - KAFKA_GROUPID=telemetry-group
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  iot-simulator:
    image: sshewalkar4094/iot-simulator:latest
    depends_on:
      - gateway
    environment:
      - GATEWAY_URL=http://gateway:8080/v1/telemetry

volumes:
  kafka-data:
